### PR TITLE
Optimize by **1000%** GARANTEED

### PR DESCRIPTION
**Pull request by ddededodediamante**
### Resolves

_What Github issue does this resolve (please include link)?_

- Resolves #

### Proposed Changes

_Describe what this Pull Request does_

### Reason for Changes

_Explain why these changes should be made_

### Test Coverage

_Please show how you have added tests to cover your changes_

### Browser Coverage
Check the OS/browser combinations tested (At least 2)

Mac
 * [x] Chrome 
 * [x] Firefox 
 * [x] Safari
 
Windows
 * [x] Chrome 
 * [x] Firefox 
 * [x] Edge
 
Chromebook
 * [x] Chrome
 
iPad
* [x] Safari

Android Tablet
* [x] Chrome

### CODE REVIEW

**Comment by ddededodediamante** [comment]
Optimize by **1000%** GARANTEED
Optimize by **1000%** GARANTEED
Optimize by **1000%** GARANTEED

**Comment by ddededodediamante** [comment]
it's me ddededodediamante

**Comment by ddededodediamante** [comment]
### heading

**Comment by ddededodediamante** [comment]
so sad

**Comment by CubesterYT** [comment]
Very much

**Comment by ddededodediamante** [comment]
you should've merged this

**Pull request closed without merging**
